/**
 * WordPress dependencies
 */
import {
	Button,
	Modal,
	__experimentalHStack as HStack,
	__experimentalVStack as VStack,
	TextControl,
	CheckboxControl,
	TextareaControl,
	Tooltip,
} from '@wordpress/components';
import { __, sprintf } from '@wordpress/i18n';
import { useDispatch, useRegistry, useSelect } from '@wordpress/data';
import { useState } from '@wordpress/element';
import { store as coreStore } from '@wordpress/core-data';
import { store as noticesStore } from '@wordpress/notices';
import { decodeEntities } from '@wordpress/html-entities';
import {
	serialize,
	synchronizeBlocksWithTemplate,
	createBlock,
} from '@wordpress/blocks';

export default function AddNewPostModal( { postType, onSave, onClose } ) {
	const labels = useSelect(
		( select ) => select( coreStore ).getPostType( postType )?.labels,
		[ postType ]
	);
	const [ isCreatingPost, setIsCreatingPost ] = useState( false );
	const [ title, setTitle ] = useState( '' );
	const [ withAI, setWithAI ] = useState( false );
	const [ showInstructions, setShowInstructions ] = useState( false );
	const [ instructions, setInstructions ] = useState( '' );

	const { saveEntityRecord } = useDispatch( coreStore );
	const { createErrorNotice, createSuccessNotice } =
		useDispatch( noticesStore );
	const { resolveSelect } = useRegistry();

	async function createPost( event ) {
		event.preventDefault();

		if ( isCreatingPost ) {
			return;
		}
		setIsCreatingPost( true );
		try {
			const postTypeObject =
				await resolveSelect( coreStore ).getPostType( postType );

			let content;
			if ( withAI ) {
				// Create placeholder blocks to showcase AI-generated content
				const placeholderBlocks = [
					createBlock( 'core/paragraph', {
						content: instructions
							? `AI will generate content based on: "${ instructions }"`
							: 'AI-generated introduction paragraph based on the page title and existing site content will appear here.',
					} ),
					createBlock( 'core/heading', {
						content: 'Key Section',
						level: 2,
					} ),
					createBlock( 'core/paragraph', {
						content:
							'This section will be populated with relevant content generated by AI, taking into account your existing pages and site styles.',
					} ),
					createBlock( 'core/columns', {}, [
						createBlock( 'core/column', {}, [
							createBlock( 'core/paragraph', {
								content:
									'AI-generated content in first column.',
							} ),
						] ),
						createBlock( 'core/column', {}, [
							createBlock( 'core/paragraph', {
								content:
									'AI-generated content in second column.',
							} ),
						] ),
					] ),
				];
				content = serialize( placeholderBlocks );
			} else {
				content =
					!! postTypeObject.template &&
					postTypeObject.template.length
						? serialize(
								synchronizeBlocksWithTemplate(
									[],
									postTypeObject.template
								)
						  )
						: undefined;
			}

			const newPage = await saveEntityRecord(
				'postType',
				postType,
				{
					status: 'draft',
					title,
					slug: title ?? undefined,
					content,
				},
				{ throwOnError: true }
			);

			onSave( newPage );

			createSuccessNotice(
				sprintf(
					// translators: %s: Title of the created post or template, e.g: "Hello world".
					__( '"%s" successfully created.' ),
					decodeEntities( newPage.title?.rendered || title ) ||
						__( '(no title)' )
				),
				{ type: 'snackbar' }
			);
		} catch ( error ) {
			const errorMessage =
				error.message && error.code !== 'unknown_error'
					? error.message
					: __( 'An error occurred while creating the item.' );

			createErrorNotice( errorMessage, {
				type: 'snackbar',
			} );
		} finally {
			setIsCreatingPost( false );
		}
	}

	return (
		<Modal
			title={
				// translators: %s: post type singular_name label e.g: "Page".
				sprintf( __( 'Draft new: %s' ), labels?.singular_name )
			}
			onRequestClose={ onClose }
			focusOnMount="firstContentElement"
			size="small"
		>
			<form onSubmit={ createPost }>
				<VStack spacing={ 4 }>
					<TextControl
						__next40pxDefaultSize
						__nextHasNoMarginBottom
						label={ __( 'Title' ) }
						onChange={ setTitle }
						placeholder={ __( 'No title' ) }
						value={ title }
					/>
					<HStack justify="space-between">
						<Tooltip
							text={ __(
								'The page will be created based on the title, existing pages, content, and styles.'
							) }
						>
							<div>
								<CheckboxControl
									__nextHasNoMarginBottom
									label={ __( 'With AI' ) }
									checked={ withAI }
									onChange={ ( checked ) => {
										setWithAI( checked );
										if ( ! checked ) {
											setShowInstructions( false );
										}
									} }
								/>
							</div>
						</Tooltip>
						{ withAI && (
							<Button
								variant="link"
								onClick={ () =>
									setShowInstructions( ! showInstructions )
								}
								style={ { color: '#949494' } }
							>
								{ __( 'add instructions' ) }
							</Button>
						) }
					</HStack>
					{ withAI && showInstructions && (
						<TextareaControl
							__nextHasNoMarginBottom
							label={ __( 'Instructions' ) }
							value={ instructions }
							onChange={ setInstructions }
							placeholder={ __(
								'e.g., Include a hero section with a call-to-action, add customer testimonials, use a modern layout with images...'
							) }
							rows={ 4 }
						/>
					) }
					<HStack spacing={ 2 } justify="end">
						<Button
							__next40pxDefaultSize
							variant="tertiary"
							onClick={ onClose }
						>
							{ __( 'Cancel' ) }
						</Button>
						<Button
							__next40pxDefaultSize
							variant="primary"
							type="submit"
							isBusy={ isCreatingPost }
							aria-disabled={ isCreatingPost }
						>
							{ __( 'Create draft' ) }
						</Button>
					</HStack>
				</VStack>
			</form>
		</Modal>
	);
}
